[build]
  base = "/"
  command = "npm run build"
  publish = "build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./server.js"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 